title: "Daniel Wanjama"
description: "Cybersecurity | Identity & Governance | Offensive Security"
author:
  name: "Daniel Wanjama"
  avatar: "/assets/images/profile.jpg"
  bio: "Cloud enthusiast focused on Microsoft security technologies"
  location: "Kenya"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/danielwanjama"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/danielwanjama"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:daniel.wanjama@email.com"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
